#Auth Data
ora_user: your_username
ora_user_pass: your_password

#Config
ora_db_list_file: "/opt/ora-audit/config/db.csv"
key_list: "/opt/ora-audit/config/key.csv"
exclude_status: False
exclude_key_list: "/opt/ora-audit/config/exclude_key.csv"

#Report
report_file: "/opt/ora-audit/report/report.csv"

#Log
error_log: "/opt/ora-audit/log/error.log"

#Lib
oracle_lib_dir: "/opt/ora-audit/lib/windows/instantclient_19_11"
